version: '2'

services:
  rocketchat:
    image: rocketchat/rocket.chat:latest
    restart: unless-stopped
    volumes:
      - /srv/docker/rocketchat/uploads:/app/uploads
      - /etc/localtime:/etc/localtime:ro    
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
    #  - HTTP_PROXY=http://proxy.domain.com
    #  - HTTPS_PROXY=http://proxy.domain.com
    depends_on:
      - mongo
      - mongo-init-replica
    #ports:
    #  - 8080:3000
    labels:
      - "traefik.enable=true"
      - "traefik.backend=rocketchat"
      - "traefik.frontend.rule=Host:host.name.local"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.passHostHeader=true"

  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
     - /srv/docker/mongo/data/db:/data/db
     - /etc/localtime:/etc/localtime:ro
     #- ./data/dump:/dump
    command: mongod --smallfiles --oplogSize 128 --replSet rs0
    labels:
      - "traefik.enable=false"

  # this container's job is just run the command to initialize the replica set.
  # it will run the command and remove himself (it will not stay running)
  mongo-init-replica:
    image: mongo:3.2
    command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'
    depends_on:
      - mongo

  # hubot, the popular chatbot (add the bot user first and change the password before starting this image)
  hubot:
    image: rocketchat/hubot-rocketchat:latest
    restart: unless-stopped
    environment:
      - ROCKETCHAT_URL=rocketchat:3000
      - ROCKETCHAT_ROOM=ROOM
      - ROCKETCHAT_USER=hubot
      - ROCKETCHAT_PASSWORD=password
      - BOT_NAME=hubot
  # you can add more scripts as you'd like here, they need to be installable by npm
      - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
    depends_on:
      - rocketchat
    labels:
      - "traefik.enable=false"
    volumes:
      - /srv/docker/hubot/scripts:/home/hubot/scripts
      - /etc/localtime:/etc/localtime:ro
  # this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
  #  ports:
  #    - 3001:8080

  traefik:
    image: traefik:latest
    restart: unless-stopped
    command: --docker --docker.domain=docker.domain.local --docker.exposedbydefault=false
    ports:
      - 8080:8080
      - 8081:8081
      - 8443:8443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml:ro
      - /etc/ssl/fullchain.pem:/etc/ssl.cert:ro
      - /etc/ssl/privkey.pem:/etc/ssl.key:ro
      - /etc/localtime:/etc/localtime:ro

